name: Custom Armbian Build

on:
  workflow_dispatch:
    inputs:
      board:
        description: 'Board name'
        required: true
        default: 'x96q'
      branch:
        description: 'Branch'
        required: true
        default: 'current'
      release:
        description: 'Release'
        required: true
        default: 'trixie'
      - name: Fix COLUMNS env
         run: |
         unset COLUMNS
          echo "COLUMNS=160" >> $GITHUB_ENV
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Armbian
        env:
          COLUMNS: "160"
        run: |
          sudo ./compile.sh build \
            BOARD=${{ github.event.inputs.board }} \
            BRANCH=${{ github.event.inputs.branch }} \
            RELEASE=${{ github.event.inputs.release }} \
            BUILD_DESKTOP=yes \
            BUILD_MINIMAL=no \
            DESKTOP_APPGROUPS_SELECTED= \
            DESKTOP_ENVIRONMENT=xmonad \
            DESKTOP_ENVIRONMENT_CONFIG_NAME=config_base \
            KERNEL_CONFIGURE=no \
            EXPERT=yes \
            KERNEL_BTF=no

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-${{ github.event.inputs.board }}
          path: output/images/*.img.xz
          retention-days: 7
          - name: Fix COLUMNS env
       
